version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn initialize:app --reload --port=80 --host=0.0.0.0"
    ports:
      - 80:80
    volumes:
      - .:/app
    env_file:
      - .env